#
# Copyright (C) 2025 Salvo Giangreco
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# UN1CA configuration file for Exynos devices (essi/essi_64)

# Galaxy S25 FE (Exynos) (One UI 8.5)
SOURCE_CODENAME="r13s"
SOURCE_FIRMWARE="SM-S731B/EUX/RZCY828JTZM"
SOURCE_EXTRA_FIRMWARES=()
SOURCE_PLATFORM_SDK_VERSIOSN=36
SOURCE_API_LEVEL=36
SOURCE_PRODUCT_FIRST_API_LEVEL=36
SOURCE_VNDK_VERSION="34"
SOURCE_SUPER_GROUP_NAME="group_basic"
SOURCE_HAS_SYSTEM_EXT=true

# SEC Product Feature
SOURCE_AUTO_BRIGHTNESS_TYPE="5"
SOURCE_DVFS_CONFIG_NAME="dvfs_policy_default"
SOURCE_AUDIO_CONFIG_RECORDALIVE_LIB_VERSION="08020"
SOURCE_AUDIO_SUPPORT_ACH_RINGTONE=true
SOURCE_AUDIO_SUPPORT_DUAL_SPEAKER=true
SOURCE_AUDIO_SUPPORT_VIRTUAL_VIBRATION=true
SOURCE_CAMERA_SUPPORT_CAMERAX_EXTENSION=true
SOURCE_CAMERA_SUPPORT_CUTOUT_PROTECTION=false
SOURCE_CAMERA_SUPPORT_MASS_APP_FLAVOR=false
SOURCE_CAMERA_SUPPORT_SDK_SERVICE=true
SOURCE_MDNIE_SUPPORTED_MODES="37905"
SOURCE_COMMON_SUPPORT_DYN_RESOLUTION_CONTROL=false
SOURCE_IS_ESIM_SUPPORTED=true
SOURCE_COMMON_SUPPORT_HDR_EFFECT=true
SOURCE_DVFSAPP_CONFIG_DVFS_POLICY_FILENAME="dvfs_policy_default"
SOURCE_DVFSAPP_CONFIG_SSRM_POLICY_FILENAME="siop_r13s_s5e9945"
SOURCE_FP_SENSOR_CONFIG="google_touch_display_optical,settings=3,aod_transition_animation"
SOURCE_HAS_HW_MDNIE=false
SOURCE_HAS_MASS_CAMERA_APP=true
SOURCE_HAS_QHD_DISPLAY=false
SOURCE_HFR_MODE="2"
SOURCE_MDNIE_WEAKNESS_SOLUTION_FUNCTION="0"
SOURCE_HFR_SUPPORTED_REFRESH_RATE="60,120"
SOURCE_HFR_DEFAULT_REFRESH_RATE="120"
SOURCE_DISPLAY_CUTOUT_TYPE="center"
SOURCE_HFR_SEAMLESS_BRT="89,91"
SOURCE_HFR_SEAMLESS_LUX="260,2500"
SOURCE_LCD_CONFIG_SEAMLESS_BRT="84,85"
SOURCE_LCD_CONFIG_SEAMLESS_LUX="200,1500"
SOURCE_LCD_SUPPORT_MDNIE_HW=true
SOURCE_RIL_FEATURES="onebinary satellite_carrier"
SOURCE_RIL_SIM_CONFIG_MULTISIM_TRAYCOUNT="1"
SOURCE_RIL_SUPPORT_WATERPROOF_SIM_TRAY_MSG=true
SOURCE_SECURITY_CONFIG_ESE_CHIP_VENDOR="NXP"
SOURCE_SECURITY_CONFIG_ESE_COS_NAME="JCOP6.2U"
SOURCE_WLAN_CONFIG_CONNECTION_PERSONALIZATION="1"
SOURCE_WLAN_CONFIG_CPU_CSTATE_DISABLE_THRESHOLD="100"
SOURCE_WLAN_CONFIG_CUSTOM_BACKOFF="CAM_FRONT -1 -1 -1 -1 14 10 UWB_5G_CX 36 177"
SOURCE_WLAN_CONFIG_DATA_ACTIVITY_AFFINITY_BOOSTER_THRESHOLD="0"
SOURCE_WLAN_CONFIG_DYNAMIC_SWITCH="15"
SOURCE_WLAN_CONFIG_L1SS_DISABLE_THRESHOLD="0"
SOURCE_WLAN_SUPPORT_80211AX=true
SOURCE_WLAN_SUPPORT_80211AX_6GHZ=false
SOURCE_WLAN_SUPPORT_APE_SERVICE=true
SOURCE_WLAN_SUPPORT_LOWLATENCY=true
SOURCE_WLAN_SUPPORT_MBO=true
SOURCE_WLAN_SUPPORT_MOBILEAP_5G_BASEDON_COUNTRY=false
SOURCE_WLAN_SUPPORT_MOBILEAP_6G=false
SOURCE_WLAN_SUPPORT_MOBILEAP_DUALAP=false
SOURCE_WLAN_SUPPORT_MOBILEAP_OWE=false
SOURCE_WLAN_SUPPORT_MOBILEAP_POWER_SAVEMODE=true
SOURCE_WLAN_SUPPORT_MOBILEAP_PRIORITIZE_TRAFFIC=true
SOURCE_WLAN_SUPPORT_MOBILEAP_WIFI_CONCURRENCY=false
SOURCE_WLAN_SUPPORT_MOBILEAP_WIFISHARING_LITE=false
SOURCE_WLAN_SUPPORT_SWITCH_FOR_INDIVIDUAL_APPS=true
SOURCE_WLAN_SUPPORT_TWT_CONTROL=true
SOURCE_WLAN_SUPPORT_WIFI_TO_CELLULAR=true